### ISSUE TITLE
Using the CDN causes download errors

### ISSUE THREAD

**Issue by ftrotter** [GraphAlchemist/Alchemy#343]
Apparently issues with fonts...

http://screencast.com/t/cG6c912OEM7N

Getting 403 forbidden on the files, which is strange, given that you can easily open them in the browser tab...

-FT

**Comment by valtih1978** [comment]
I do not know what was resolved but I am getting 403 for both

	<link rel="stylesheet" href="http://cdn.graphalchemist.com/alchemy.0.2.min.css"/>
	<script type="text/javascript" src="http://cdn.graphalchemist.com/alchemy.0.2.min.js"></script>

It is curious, that I still can load these files when entering these urls into browser addrss bar.

**Comment by valtih1978** [comment]
I do not know what was resolved but I am getting 403 Forbidden for

	<script type="text/javascript" src="http://cdn.graphalchemist.com/alchemy.0.2.min.js"></script>

So, I do not understand who are [your examples](http://graphalchemist.github.io/Alchemy/#/docs) are inteded for.

It is curious though, that I still can load these files when entering file's url into the browser addrss bar manualy.
