### ISSUE TITLE
Documentation: reconfigure on the fly

### ISSUE THREAD

**Issue by ftrotter** [GraphAlchemist/Alchemy#398]
Is there a way to reset configuration variables, and restart the graph layout?

If so is there a way to add examples of this to the documentation. As it stands it seems like you make a lot of config decisions up front and then its not simple to change them after...

-FT

**Comment by Swimminschrage** [comment]
I agree.  I'm looking to update the graph on the fly as the result of additional nodes/edges being queried for, but I'm not finding a way to do it without calling "startGraph" again which ends up creating a second SVG of the graph.
