### ISSUE TITLE
Maintaining Alchemy

### ISSUE THREAD

**Issue by kylerob** [GraphAlchemist/Alchemy#553]
I'm interested in maintaining the project and moving it forward with new features. A few coworkers of mine have also expressed interest (BTI360).

**Comment by VelocityDB** [comment]
I tried the simple sample in my own html page, when I try to see it in browser, I just get a blank page. Any ideas?

**Comment by kylerob** [comment]
@VelocityDB Do you see any errors in the chrome or ff debug consoles? If so, can you please post the error information here?

**Comment by VelocityDB** [comment]
I do see some errors for java script in Visual studio java script console:

 

04:45:38.1697: Referenced file '~/wwwRoot/_references.js' not found.

04:45:38.1697: Referenced file '~/Scripts/_references.js' not found.

04:45:38.1697: Downloading referenced file 'http://cdn.graphalchemist.com/alchemy.min.js'...

04:45:40.2720: 'http://cdn.graphalchemist.com/alchemy.min.js' download completed.

04:46:59.6484: Referenced file '~/wwwRoot/_references.js' not found.

04:46:59.6484: Referenced file '~/Scripts/_references.js' not found.

04:46:59.6484: Downloading referenced file 'http://cdn.graphalchemist.com/alchemy.min.js'...

04:47:02.2179: 'http://cdn.graphalchemist.com/alchemy.min.js' download completed.

04:47:17.7990: Referenced file '~/wwwRoot/_references.js' not found.

04:47:17.7990: Referenced file '~/Scripts/_references.js' not found.

04:47:17.7990: Downloading referenced file 'http://cdn.graphalchemist.com/alchemy.min.js'...

04:47:19.9057: 'http://cdn.graphalchemist.com/alchemy.min.js' download completed.

 

I attached 2 of the html files I tried with. I have a data directory in same directory as these 2 html files. And it contains a charlize.json file.

**Comment by hdngr** [comment]
@kylerob - can you shoot me an email with a little more about your firm, why you want to maintain alchemy, and anything else...  Thanks!

hstnhdngr@gmail.com

**Comment by kylerob** [comment]
Hi, I sent an email a week or two back and haven't heard anything. Did it go to your spam folder?

**Comment by VelocityDB** [comment]
Hi Kyle,

 

I did send an email back.

**Comment by kylerob** [comment]
@VelocityDB, I'm going to push out a new release within a week, at which point I'll have you try the example again and see if you run into any issues. I'm going to close this issue out until then. Please open a new issue if you do run into any further problems after the new release.
