### ISSUE TITLE
Uncaught TypeError: conf.graphWidth is not a function

### ISSUE THREAD

**Issue by myxibrium** [GraphAlchemist/Alchemy#584]
I copied the HTML from the homepage here: http://graphalchemist.github.io/Alchemy/#/

And copied the individual files from the download link on the same page, which points here: https://github.com/GraphAlchemist/Alchemy/releases/download/0.4.1/0.4.1.zip

And I get the following error:
Uncaught TypeError: conf.graphWidth is not a function
    at alchemy.js:sourcemap:1281
    at vendor.js:4
    at Object.<anonymous> (vendor.js:4)
    at Object.b (vendor.js:4)
    at XMLHttpRequest.e (vendor.js:4)

In the HTML example, graphWidth and graphHeight are not defined as functions. But why should they be?

**Comment by myxibrium** [comment]
I fixed the issue by changing the html:
    graphHeight: function() {return 260},
    graphWidth: function() {return 300},

Home page should be updated with latest example.

**Comment by hdngr** [comment]
@myxibrium this library is not supported.  That should be obvious from the Readme.
